POST http://localhost:3002/buy/crypto HTTP/1.1
content-type: application/json

{
    "fiatAmount": "22.3",
    "address":"000xxxx",
    "firstName": "João",
    "lastName": "Da Silva",
    "document": "07326132054",
    "email": "teste@picpay.com",
    "phone": "+55 27 12345-6789"
}